---
- hosts: gateways 
  remote_user: root
  roles:
    - { role: hostname, tags: "hostname"}
    - { role: common, tags: "common"}
    - { role: backports-kernel, tags: "backports-kernel"}
    - { role: ip_forwarding, tags: "ip_forwarding"}
    - { role: gateways_gre, tags: "gateways_gre"}
    - { role: gateways_batman, tags: "gateways_batman"}
    - { role: gateways_gretap, tags: "gateways_gretap"}
    - { role: gateways_bird, tags: "gateways_bird"}
#    - { role: dhcp, tags: "dhcp"}
#    - { role: bind_gateway, tags: "bind_gateway"}
#    - { role: collectd, tags: "collectd"}
