# Playbook zur Konfiguration aller Servern von services

- hosts: services
  remote_user: root
  roles:
#    - interfaces-gretap
    - collectd
    - interfaces_services
    - alfred_json
    - ffmap_backend
    - meshviewer

