# Playbook zur Konfiguration aller Servern von services

- hosts: services
  remote_user: root
  roles:
    #- collectd
    - backports-kernel
#    - interfaces-gretap
    - interfaces_services
    - alfred_json
    - ffmap_backend
    - nginx
    - meshviewer

