---
# Playbook zur Konfiguration von Supernode Servern 

- hosts: supernodes
  remote_user: root
  roles:
#    - { role: fastd, tags: "fastd"} # 
    - { role: ipforwarding, tags: "ip_forwarding"}
    - { role: collectd, tags: "collectd"}

