---
# Tasks for network interfaces

# adding ffrl natv4 address to loopback adapter
# usage of regex insted of ipaddr filters because address space is used as point-to-point and sometimes the netaddress is used as "normal" address and this is not handable with ipaddr filters
- name: Create interfaces - add ffrl to loopback
  lineinfile: 
     dest='/etc/network/interfaces'
     regexp='^[ \t]+up ip address add.*$'
     insertafter='^iface lo inet loopback.*$'
     line='        up ip address add {{server_ipv4_nat | regex_replace("^(\d+\.\d+\.\d+\.\d+)/\d+$","\\1")}}/32 dev lo'
  notify:
    - restart networking

# note: python-netaddr is required on ansible host

# todo: apt-get der entsprechenden pakete

# creating bridge interface
- name: Create interfaces - bridge file
  template: src="bridge.j2" dest="/etc/network/interfaces.d/10_bridge.cfg"
  notify:
    - restart networking

# creating batman interface
- name: Create interfaces - batman file
  template: src="batman.j2" dest="/etc/network/interfaces.d/20_batman.cfg"
  notify:
    - restart networking

- name: Create interfaces - gretap file
  template: src="gretap.j2" dest="/etc/network/interfaces.d/30_gretap.cfg"
  notify:
    - restart networking

# creating gretap tunnels to ffrl
- name: Create interfaces - gretap to ffrl
  template: src="gre_ffrl.j2" dest="/etc/network/interfaces.d/40_gre_ffrl.cfg"
  notify:
    - restart networking

#append line in interfaces file for reading additional config files
- name: let read interfaces from interfaces
  lineinfile: dest="/etc/network/interfaces" line="source /etc/network/interfaces.d/*.cfg"
  notify:
    - restart networking