- name: Schl端ssel f端r Bird hinzuf端gen
  apt_key: keyserver=keyserver.ubuntu.com id=AC0E47584A7A714D

- name: Bird-Repo hinzuf端gen
  apt_repository:
        repo: "deb http://bird.network.cz/debian/ jessie main"
        state: present

- name: Bird installieren
  apt:
        repo: "{{item}}"
        update_cache: yes
        state: installed
  with_items:
        - bird
        - bird6
        
