---

- name: install apt packages
  apt:
    pkg: "{{ item }}"
    update_cache: yes
    state: installed
  with_items:
    - python 
    - python-pip
    - python-dev
    
- name: install zope.interface
  pip: 
    name: zope.interface 
    version: 3.6.0
    state: present 

- name: install whisper
  pip: 
    name: whisper 
    version: 0.9.15
    state: present 
    extra_args: '--install-option="--prefix=/var/lib/graphite" --install-option="--install-lib=/var/lib/graphite/lib" '
    
- name: install carbon
  pip: 
    name: carbon 
    version: 0.9.15
    state: present
    extra_args: '--install-option="--prefix=/var/lib/graphite" --install-option="--install-lib=/var/lib/graphite/lib" '

- name: install graphite-web
  pip: 
    name: graphite-web 
    version: 0.9.15
    state: present
    extra_args: '--install-option="--prefix=/var/lib/graphite" --install-option="--install-lib=/var/lib/graphite/lib" '

- name: copy file 
  copy: src=carbon.conf dest=/var/lib/graphite/conf/ 

- name: copy file 
  copy: src=storage-schemas.conf dest=/var/lib/graphite/conf/ 

- name: copy file 
  copy: src=graphite.wsgi dest=/var/lib/graphite/conf/ 

- name: copy file 
  copy: src=local_settings.py dest=/var/lib/graphite/lib/graphite/ 

