# install bind9 service 
---
- name: install bind9
  apt: pkg=bind9 state=installed

- name: deploy named.conf.local
  template: src=named.conf.local.j2 dest=/etc/bind/named.conf.local
  notify:
    - restart bind9

- name: deploy named.conf.options
  template: src=named.conf.options.j2 dest=/etc/bind/named.conf.options
  notify:
    - restart bind9
